config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  post :home, to: "home#getBCN", as: :getbcn

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def getMonthBCN(month, year)
    require 'savon'

    client = Savon.client wsdl: 'https://servicios.bcn.gob.ni/Tc_Servicio/ServicioTC.asmx?WSDL', convert_request_keys_to: :camelcase

    message = { Ano: year, Mes: month }

    response = client.call(:recupera_tc_mes, message: message)

    result = response.body

    tasa = result[:recupera_tc_mes_response] [:recupera_tc_mes_result]

    tasa_info = tasa[:detalle_tc][:tc]

    $tasa_mes = tasa_info

    $tasa_dia = nil

    redirect_to root_path

    # respond_to do |format|
    #   format.html { redirect_to root_path, notice: 'Tasa de cambio (mes): ' + tasa_info }
    # end
  end

  def getDayBCN(day, month, year)
    require 'savon'

    client = Savon.client wsdl: 'https://servicios.bcn.gob.ni/Tc_Servicio/ServicioTC.asmx?WSDL', convert_request_keys_to: :camelcase

    message = { Ano: year, Mes: month, Dia: day }

    response = client.call(:recupera_tc_dia, message: message)

    result = response.body

    tasa = result[:recupera_tc_dia_response] [:recupera_tc_dia_result]

    $tasa_dia = tasa

    $tasa_mes = nil

    redirect_to root_path

    # respond_to do |format|
    #   format.html { redirect_to root_path, notice: 'Tasa de cambio: ' + tasa.to_s }
    # end
  end

  def getBCN
    opcion = begin
               params[:opcion]
             rescue
               nil
             end

    ano = params['fecha(1i)'].to_i
    mes = params['fecha(2i)'].to_i
    dia = params['fecha(3i)'].to_i

    if opcion == '0'
      getDayBCN(dia, mes, ano)

    else
      getMonthBCN(mes, ano)

  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 text-center">

      <h1>Tasa de cambio BCN</h1>

      <%= bootstrap_form_tag url: getbcn_path, layout: :horizontal, label_errors: true do |f| %>
      <div class="col-md-10">
        <%= f.date_select :fecha, hide_label: true %>
      </div>

      <div class="controls form">
        <div class="col-md-12">
          <%= f.radio_button :opcion, 0, label: "Obtener tasa del dia", checked: true %>
          <%=   f.radio_button :opcion, 1, label: "Obtener tasa del mes" %>
        </div>
      </div>

      <div class="form-group">

        <div class="col-md-12 text-center">
          <%= f.submit 'Obtener' , class: "btn btn-success" %>
        </div>
      </div>

      <% end %>

    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 text-center">
      <div class="alert alert-success text-center" role="alert">

        <!-- Tasa día -->
        <% if $tasa_dia.present? then %>
        <p>Tasa de cambio:
          <%= $tasa_dia.to_s %></p>

      <% else %>
        <!-- <p>Error al obtener tasa diaria</p> -->
        <% end %>
        <!-- End Tasa día -->

        <!-- Tasa mes -->
        <% if $tasa_mes.present? then %>
        <ul>
          <% $tasa_mes.each do |tasa_detalle| %>
          <li>
            <p>
              <strong>Fecha:</strong>
              <%= tasa_detalle[:fecha].to_s %>
              <strong>-></strong>
              <strong>Tasa:</strong>
              <%= tasa_detalle[:valor] %>
            </p>
          </li>
          <% end %>
        </ul>

      <% else %>
        <!-- <p>Error al obtener tasa mensual</p> -->
        <% end %>
        <!-- End Tasa mes -->

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TipoCambioBCN</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>